name: legalize
description: Checks for/sanitizes illegal characters in file names for different platforms.
version: 1.2.0
repository: https://github.com/Caesarovich/legalize

environment:
  sdk: ^3.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
